name: Fetch Latest Linux Kernel v6.x Tar.xz

on:
  schedule:
    - cron: "0 12 * * *" # Runs every day at 12:00 UTC
  workflow_dispatch: # Allows manual triggering of the action
  push:
    branches:
      - main

jobs:
  get-latest-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch and Inspect Page Content
        id: fetch_page
        run: |
          # Fetch the list of v6.x tar.xz files from kernel.org
          KERNEL_URL="https://www.kernel.org/pub/linux/kernel/v6.x/"
          echo "Fetching kernel list from $KERNEL_URL"
          
          # Store the fetched page content for debugging
          curl -s $KERNEL_URL > page_content.html
          
          # Output the fetched page content (for debugging purposes)
          echo "Fetched page content:"
          cat page_content.html

      - name: Extract Latest Linux Kernel v6.x Version
        id: extract_kernel
        run: |
          # Extract the latest linux-6.x.x.tar.xz file using grep and regex
          LATEST_KERNEL_TAR_XZ=$(grep -oP 'linux-\K6\.[\d.]+(?=\.tar\.xz)' page_content.html | sort -V | tail -n 1)

          if [ -z "$LATEST_KERNEL_TAR_XZ" ]; then
            echo "Error: Failed to find the latest Linux v6.x tar.xz file"
            exit 1
          fi

          # Construct the full URL of the tar.xz file
          TAR_XZ_LINK="https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${LATEST_KERNEL_TAR_XZ}.tar.xz"
          
          echo "Latest Kernel v6.x Version: $LATEST_KERNEL_TAR_XZ"
          echo "Kernel tar.xz Link: $TAR_XZ_LINK"

          # Export the link as an environment variable
          echo "TAR_XZ_LINK=$TAR_XZ_LINK" >> $GITHUB_ENV

      - name: Save Kernel tar.xz Link to kernel.txt
        run: |
          echo "${{ env.TAR_XZ_LINK }}" > kernel.txt

      - name: Commit kernel.txt to the repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add kernel.txt
          git commit -m "Update kernel.txt with latest v6.x kernel tar.xz link"
          
          # Use the built-in GITHUB_TOKEN for authentication
          git push https://github.com/brrock/myos.git HEAD:main
